//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWE_Project_LibDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SWEProjectModelContainer : DbContext
    {
        public SWEProjectModelContainer()
            : base("name=SWEProjectModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Projekt> Projekts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Kommentar> Kommentars { get; set; }
        public virtual DbSet<Bewertung> Bewertungen { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
    }
}
